# Generated by Django 2.2.7 on 2019-11-08 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('logdbapp', '0002_auto_20191104_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
