# Generated by Django 2.2.7 on 2019-11-10 17:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logdbapp', '0003_useraddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_History',
            fields=[
                ('user_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_history_username', models.CharField(max_length=100)),
                ('user_history_action', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='UserAddress',
            new_name='User_Address',
        ),
    ]
