# Generated by Django 2.2.7 on 2019-11-18 17:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logdbapp', '0004_auto_20191110_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_history',
            name='user_history_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
